# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-27 02:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntl', models.BooleanField(default=False)),
                ('cdntt', models.BooleanField(default=False)),
                ('cdod', models.BooleanField(default=False)),
                ('dyush', models.BooleanField(default=False)),
                ('ndshi', models.BooleanField(default=False)),
                ('kytalyk', models.BooleanField(default=False)),
                ('custom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ConferenceResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[(b'1', b'\xd0\xa8\xd0\xba\xd0\xbe\xd0\xbb\xd1\x8c\xd0\xbd\xd1\x8b\xd0\xb9'), (b'2', b'\xd0\x9a\xd1\x83\xd1\x81\xd1\x82\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xb9'), (b'3', b'\xd0\xa0\xd0\xb0\xd0\xb9\xd0\xbe\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb9'), (b'4', b'\xd0\xa0\xd0\xb5\xd0\xb3\xd0\xb8\xd0\xbe\xd0\xbd\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xbd\xd1\x8b\xd0\xb9'), (b'5', b'\xd0\xa0\xd0\xb5\xd1\x81\xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xb0\xd0\xbd\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9'), (b'6', b'\xd0\x92\xd1\x81\xd0\xb5\xd1\x80\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd0\xb9\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9'), (b'7', b'\xd0\x9c\xd0\xb5\xd0\xb6\xd0\xb4\xd1\x83\xd0\xbd\xd0\xb0\xd1\x80\xd0\xbe\xd0\xb4\xd0\xbd\xd1\x8b\xd0\xb9')], max_length=1)),
                ('section', models.CharField(choices=[(b'INF', b'\xd0\x98\xd0\xbd\xd1\x84\xd0\xbe\xd1\x80\xd0\xbc\xd0\xb0\xd1\x82\xd0\xb8\xd0\xba\xd0\xb0'), (b'MAT', b'\xd0\x9c\xd0\xb0\xd1\x82\xd0\xb5\xd0\xbc\xd0\xb0\xd1\x82\xd0\xb8\xd0\xba\xd0\xb0')], max_length=3)),
                ('name', models.CharField(max_length=50)),
                ('adviser', models.CharField(max_length=50)),
                ('result', models.CharField(choices=[(b'1', b'\xd0\x9b\xd0\xb0\xd1\x83\xd1\x80\xd0\xb5\xd0\xb0\xd1\x82'), (b'2', b'\xd0\x94\xd0\xb8\xd0\xbf\xd0\xbb\xd0\xbe\xd0\xbc\xd0\xb0\xd0\xbd\xd1\x82 1 \xd1\x81\xd1\x82\xd0\xb5\xd0\xbf\xd0\xb5\xd0\xbd\xd0\xb8'), (b'3', b'\xd0\x94\xd0\xb8\xd0\xbf\xd0\xbb\xd0\xbe\xd0\xbc\xd0\xb0\xd0\xbd\xd1\x82 2 \xd1\x81\xd1\x82\xd0\xb5\xd0\xbf\xd0\xb5\xd0\xbd\xd0\xb8'), (b'4', b'\xd0\x94\xd0\xb8\xd0\xbf\xd0\xbb\xd0\xbe\xd0\xbc\xd0\xb0\xd0\xbd\xd1\x82 3 \xd1\x81\xd1\x82\xd0\xb5\xd0\xbf\xd0\xb5\xd0\xbd\xd0\xb8')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momname', models.CharField(max_length=50)),
                ('momwork', models.CharField(max_length=50)),
                ('dadname', models.CharField(max_length=50)),
                ('dadwork', models.CharField(max_length=50)),
                ('childcount', models.CharField(max_length=50)),
                ('minorcount', models.CharField(max_length=50)),
                ('traditions', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HobbyOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.BooleanField(default=False)),
                ('science', models.BooleanField(default=False)),
                ('painting', models.BooleanField(default=False)),
                ('sport', models.BooleanField(default=False)),
                ('hunting', models.BooleanField(default=False)),
                ('cooking', models.BooleanField(default=False)),
                ('tecnology', models.BooleanField(default=False)),
                ('art', models.BooleanField(default=False)),
                ('photo', models.BooleanField(default=False)),
                ('custom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OlympResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[(b'MA', b'\xd0\xbc\xd0\xb0\xd1\x82\xd0\xb5\xd0\xbc\xd0\xb0\xd1\x82\xd0\xb8\xd0\xba\xd0\xb0'), (b'CS', b'\xd0\xb8\xd0\xbd\xd1\x84\xd0\xbe\xd1\x80\xd0\xbc\xd0\xb0\xd1\x82\xd0\xb8\xd0\xba\xd0\xb0 \xd0\xb8 \xd0\x98\xd0\x9a\xd0\xa2'), (b'PH', b'\xd1\x84\xd0\xb8\xd0\xb7\xd0\xb8\xd0\xba\xd0\xb0'), (b'CH', b'\xd1\x87\xd0\xb8\xd0\xbc\xd0\xb8\xd1\x8f'), (b'BI', b'\xd0\xb1\xd0\xb8\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb3\xd0\xb8\xd1\x8f'), (b'GE', b'\xd0\xb3\xd0\xb5\xd0\xbe\xd0\xb3\xd1\x80\xd0\xb0\xd1\x84\xd0\xb8\xd1\x8f'), (b'RL', b'\xd1\x80\xd1\x83\xd1\x81\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd1\x8f\xd0\xb7\xd1\x8b\xd0\xba \xd0\xb8 \xd0\xbb\xd0\xb8\xd1\x82\xd0\xb5\xd1\x80\xd0\xb0\xd1\x82\xd1\x83\xd1\x80\xd0\xb0'), (b'SL', b'\xd1\x8f\xd0\xba\xd1\x83\xd1\x82\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9 \xd1\x8f\xd0\xb7\xd1\x8b\xd0\xba \xd0\xb8 \xd0\xbb\xd0\xb8\xd1\x82\xd0\xb5\xd1\x80\xd0\xb0\xd1\x82\xd1\x83\xd1\x80\xd0\xb0'), (b'FL', b'\xd0\xb8\xd0\xbd\xd0\xbe\xd1\x81\xd1\x82\xd1\x80\xd0\xb0\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb9 \xd1\x8f\xd0\xb7\xd1\x8b\xd0\xba'), (b'HI', b'\xd0\xb8\xd1\x81\xd1\x82\xd0\xbe\xd1\x80\xd0\xb8\xd1\x8f'), (b'SS', b'\xd0\xbe\xd0\xb1\xd1\x89\xd0\xb5\xd1\x81\xd1\x82\xd0\xb2\xd0\xbe\xd0\xb7\xd0\xbd\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'), (b'MU', b'\xd0\xbc\xd1\x83\xd0\xb7\xd1\x8b\xd0\xba\xd0\xb0 \xd0\xb8 \xd0\xb8\xd1\x81\xd0\xba\xd1\x83\xd1\x81\xd1\x81\xd1\x82\xd0\xb2\xd0\xbe'), (b'DR', b'\xd0\x98\xd0\x97\xd0\x9e \xd0\xb8 \xd1\x87\xd0\xb5\xd1\x80\xd1\x87\xd0\xb5\xd0\xbd\xd0\xb8\xd0\xb5'), (b'TE', b'\xd1\x82\xd0\xb5\xd1\x85\xd0\xbd\xd0\xbe\xd0\xbb\xd0\xbe\xd0\xb3\xd0\xb8\xd1\x8f'), (b'LS', b'\xd0\x9e\xd0\x91\xd0\x96'), (b'PC', b'\xd1\x84\xd0\xb8\xd0\xb7\xd0\xba\xd1\x83\xd0\xbb\xd1\x8c\xd1\x82\xd1\x83\xd1\x80\xd0\xb0'), (b'AU', b'\xd0\xb0\xd0\xb2\xd1\x82\xd0\xbe\xd0\xb4\xd0\xb5\xd0\xbb\xd0\xbe'), (b'CU', b'\xd0\x9a\xd0\x9d\xd0\xa0\xd0\xa1(\xd0\xaf)')], max_length=2)),
                ('level', models.CharField(choices=[(b'1', b'\xd0\xa8\xd0\xba\xd0\xbe\xd0\xbb\xd1\x8c\xd0\xbd\xd1\x8b\xd0\xb9'), (b'2', b'\xd0\x9a\xd1\x83\xd1\x81\xd1\x82\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xb9'), (b'3', b'\xd0\xa0\xd0\xb0\xd0\xb9\xd0\xbe\xd0\xbd\xd0\xbd\xd1\x8b\xd0\xb9'), (b'4', b'\xd0\xa0\xd0\xb5\xd0\xb3\xd0\xb8\xd0\xbe\xd0\xbd\xd0\xb0\xd0\xbb\xd1\x8c\xd0\xbd\xd1\x8b\xd0\xb9'), (b'5', b'\xd0\xa0\xd0\xb5\xd1\x81\xd0\xbf\xd1\x83\xd0\xb1\xd0\xbb\xd0\xb8\xd0\xba\xd0\xb0\xd0\xbd\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9'), (b'6', b'\xd0\x92\xd1\x81\xd0\xb5\xd1\x80\xd0\xbe\xd1\x81\xd1\x81\xd0\xb8\xd0\xb9\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9'), (b'7', b'\xd0\x9c\xd0\xb5\xd0\xb6\xd0\xb4\xd1\x83\xd0\xbd\xd0\xb0\xd1\x80\xd0\xbe\xd0\xb4\xd0\xbd\xd1\x8b\xd0\xb9')], max_length=1)),
                ('result', models.CharField(choices=[(b'1', b'\xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd0\xbe\xd0\xb5 \xd0\xbc\xd0\xb5\xd1\x81\xd1\x82\xd0\xbe'), (b'2', b'\xd0\x92\xd1\x82\xd0\xbe\xd1\x80\xd0\xbe\xd0\xb5 \xd0\xbc\xd0\xb5\xd1\x81\xd1\x82\xd0\xbe'), (b'3', b'\xd0\xa2\xd1\x80\xd0\xb5\xd1\x82\xd1\x8c\xd0\xb5 \xd0\xbc\xd0\xb5\xd1\x81\xd1\x82\xd0\xbe')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SportCompetitionResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('section', models.CharField(choices=[(b'ATH', b'\xd0\x9b\xd0\xb5\xd0\xb3\xd0\xba\xd0\xb0\xd1\x8f \xd0\xb0\xd1\x82\xd0\xbb\xd0\xb5\xd1\x82\xd0\xb8\xd0\xba\xd0\xb0')], max_length=3)),
                ('trainer', models.CharField(max_length=20)),
                ('result', models.CharField(choices=[(b'1', b'\xd0\x9f\xd0\xb5\xd1\x80\xd0\xb2\xd0\xbe\xd0\xb5 \xd0\xbc\xd0\xb5\xd1\x81\xd1\x82\xd0\xbe'), (b'2', b'\xd0\x92\xd1\x82\xd0\xbe\xd1\x80\xd0\xbe\xd0\xb5 \xd0\xbc\xd0\xb5\xd1\x81\xd1\x82\xd0\xbe'), (b'3', b'\xd0\xa2\xd1\x80\xd0\xb5\xd1\x82\xd1\x8c\xd0\xb5 \xd0\xbc\xd0\xb5\xd1\x81\xd1\x82\xd0\xbe')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='SportSectionOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athletics', models.BooleanField(default=False)),
                ('weightlifting', models.BooleanField(default=False)),
                ('volleyball', models.BooleanField(default=False)),
                ('basketball', models.BooleanField(default=False)),
                ('football', models.BooleanField(default=False)),
                ('tennis', models.BooleanField(default=False)),
                ('national', models.BooleanField(default=False)),
                ('fitness', models.BooleanField(default=False)),
                ('judo', models.BooleanField(default=False)),
                ('box', models.BooleanField(default=False)),
                ('custom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[(b'5', b'5 \xd0\xba\xd0\xbb\xd0\xb0\xd1\x81\xd1\x81'), (b'6', b'6 \xd0\xba\xd0\xbb\xd0\xb0\xd1\x81\xd1\x81'), (b'7', b'7 \xd0\xba\xd0\xbb\xd0\xb0\xd1\x81\xd1\x81'), (b'8', b'8 \xd0\xba\xd0\xbb\xd0\xb0\xd1\x81\xd1\x81'), (b'9', b'9 \xd0\xba\xd0\xbb\xd0\xb0\xd1\x81\xd1\x81'), (b'10', b'10 \xd0\xba\xd0\xbb\xd0\xb0\xd1\x81\xd1\x81'), (b'11', b'11 \xd0\xba\xd0\xbb\xd0\xb0\xd1\x81\xd1\x81')], max_length=2)),
                ('letter', models.CharField(choices=[(b'A', b'\xd0\xb0'), (b'B', b'\xd0\xb1')], max_length=1)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=b'images')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[(b'M', b'\xd0\xbc\xd1\x83\xd0\xb6\xd1\x81\xd0\xba\xd0\xbe\xd0\xb9'), (b'F', b'\xd0\xb6\xd0\xb5\xd0\xbd\xd1\x81\xd0\xba\xd0\xb8\xd0\xb9')], max_length=1)),
                ('my_success', models.CharField(max_length=500)),
                ('gto', models.CharField(choices=[(b'1', b'\xd0\x97\xd0\xb0\xd1\x87\xd0\xb5\xd1\x82'), (b'2', b'\xd0\x91\xd1\x80\xd0\xbe\xd0\xbd\xd0\xb7\xd0\xb0'), (b'3', b'\xd0\xa1\xd0\xb5\xd1\x80\xd0\xb5\xd0\xb1\xd1\x80\xd0\xbe'), (b'4', b'\xd0\x97\xd0\xbe\xd0\xbb\xd0\xbe\xd1\x82\xd0\xbe'), (b'5', b'\xd0\xa3\xd1\x87\xd0\xb0\xd1\x81\xd1\x82\xd0\xb8\xd0\xb5')], max_length=1)),
                ('sections', models.CharField(max_length=50)),
                ('verified', models.BooleanField(default=False)),
                ('activity_options', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.ActivityOptions')),
                ('conference_results', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.ConferenceResult')),
                ('family', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Family')),
                ('hobby_options', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.HobbyOptions')),
                ('olymp_results', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.OlympResult')),
                ('sport_competition_results', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.SportCompetitionResult')),
                ('sport_section_options', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.SportSectionOptions')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
